#!/bin/sh

case "$1" in
    configure)
        # register address-book-app content hub rules
        content_hub_hook=$(find /usr/lib/*/content-hub -name "content-hub-peer-hook"  -executable -print0 -nowarn)
        if [ ! -z "$content_hub_hook" ]
        then
            $content_hub_hook
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
